version: 0.2
env:
  # 코드를 github에서 가져오기 위한 환경변수 설정
  git-credential-helper: yes 
  variables:
    # package 파라미터 정의
    PACKAGE_S3_BUCKET: course-netsma

phases:
  install:
    runtime-versions:
      python: 3.13

  pre_build:
    commands:
      - echo Build started on `date`

  build:
    commands:
      - echo building Source by SAM...
      #- sam build --template sns/slack/template-lambda.yml
      - sam build --template template-lambda.yml

  post_build:
    commands:
      - echo package Source...
      - sam package --s3-bucket $PACKAGE_S3_BUCKET --output-template-file outputtemplate.yml --s3-prefix build/course-aws

artifacts:
  files:
    - outputtemplate.yml
